[refactor] fix linker script to take return value of clamp-device into consideration

diff --git a/lib/clamp-link.in b/lib/clamp-link.in
--- a/lib/clamp-link.in
+++ b/lib/clamp-link.in
@@ -83,51 +83,59 @@ if [ -n "$LINK_KERNEL_ARGS" ]; then
   if [ "@HAS_OPENCL@" == "1" ]; then
     # lower to SPIR
     $CLAMP_DEVICE $TEMP_DIR/kernel.bc $TEMP_DIR/kernel.spir --spir
-  
-    # build a new kernel object
-    pushd . > /dev/null
-    cd $TEMP_DIR
-    $CLAMP_EMBED kernel.spir kernel_spir.o
-    popd > /dev/null
+    ret=$?
+    if [ $ret == 0 ]; then
+      # build a new kernel object
+      pushd . > /dev/null
+      cd $TEMP_DIR
+      $CLAMP_EMBED kernel.spir kernel_spir.o
+      popd > /dev/null
+    fi
   fi
   
   # lower to OpenCL C
   if [ "@HAS_OPENCL@" == "1" ]; then
     # lower to SPIR
     $CLAMP_DEVICE $TEMP_DIR/kernel.bc $TEMP_DIR/kernel.cl --opencl
-  
-    # build a new kernel object
-    pushd . > /dev/null
-    cd $TEMP_DIR
-    $CLAMP_EMBED kernel.cl kernel.o
-    popd > /dev/null
+    ret=$?
+    if [ $ret == 0 ]; then
+      # build a new kernel object
+      pushd . > /dev/null
+      cd $TEMP_DIR
+      $CLAMP_EMBED kernel.cl kernel.o
+      popd > /dev/null
+    fi
   fi
   
   # lower to HSA
   if [ "@HAS_HSA@" == "1" ]; then
     # lower to HSAIL
     $CLAMP_DEVICE $TEMP_DIR/kernel.bc $TEMP_DIR/kernel.brig --hsa
-  
-    # build a new kernel object
-    pushd . > /dev/null
-    cd $TEMP_DIR
-    $CLAMP_EMBED kernel.brig kernel_hsa.o
-    popd > /dev/null
+    ret=$?
+    if [ $ret == 0 ]; then
+      # build a new kernel object
+      pushd . > /dev/null
+      cd $TEMP_DIR
+      $CLAMP_EMBED kernel.brig kernel_hsa.o
+      popd > /dev/null
+    fi
   fi
   
-  # link everything together
-  if [ "@HAS_OPENCL@" == "1" ] && [ "@HAS_HSA@" == "1" ]; then
-    ld $TEMP_DIR/kernel.o $TEMP_DIR/kernel_spir.o $TEMP_DIR/kernel_hsa.o $LINK_HOST_ARGS $LINK_OTHER_ARGS
-    ret=$?
-  elif [ "@HAS_OPENCL@" == "1" ] && [ "@HAS_HSA@" == "0" ]; then
-    ld $TEMP_DIR/kernel.o $TEMP_DIR/kernel_spir.o $LINK_HOST_ARGS $LINK_OTHER_ARGS
-    ret=$?
-  elif [ "@HAS_OPENCL@" == "0" ] && [ "@HAS_HSA@" == "1" ]; then
-    ld $TEMP_DIR/kernel_hsa.o $LINK_HOST_ARGS $LINK_OTHER_ARGS
-    ret=$?
-  else
-    echo "Error in C++AMP link!"
-    ret=1
+  if [ $ret == 0 ]; then
+    # link everything together
+    if [ "@HAS_OPENCL@" == "1" ] && [ "@HAS_HSA@" == "1" ]; then
+      ld $TEMP_DIR/kernel.o $TEMP_DIR/kernel_spir.o $TEMP_DIR/kernel_hsa.o $LINK_HOST_ARGS $LINK_OTHER_ARGS
+      ret=$?
+    elif [ "@HAS_OPENCL@" == "1" ] && [ "@HAS_HSA@" == "0" ]; then
+      ld $TEMP_DIR/kernel.o $TEMP_DIR/kernel_spir.o $LINK_HOST_ARGS $LINK_OTHER_ARGS
+      ret=$?
+    elif [ "@HAS_OPENCL@" == "0" ] && [ "@HAS_HSA@" == "1" ]; then
+      ld $TEMP_DIR/kernel_hsa.o $LINK_HOST_ARGS $LINK_OTHER_ARGS
+      ret=$?
+    else
+      echo "Error in C++AMP link!"
+      ret=1
+    fi
   fi
 
 fi # if [ -n $LINK_KERNEL_ARGS ];
