support multiple search paths for ROCm Device Libs in clamp-device

diff --git a/lib/clamp-device.in b/lib/clamp-device.in
--- a/lib/clamp-device.in
+++ b/lib/clamp-device.in
@@ -51,7 +51,24 @@ LINK=$BINDIR/llvm-link
 LIB=$BINDIR/../lib
 LLD=$BINDIR/ld.lld
 
-ROCM_LIB=@ROCM_DEVICE_LIB@
+
+################
+# Determine the ROCm device libs path
+################
+
+ROCM_DEVICE_LIBS_SEARCH_PATHS="@ROCM_DEVICE_LIB@"
+ROCM_LIB=""
+for SEARCH_PATH in $(echo $ROCM_DEVICE_LIBS_SEARCH_PATHS | tr ";" "\n")
+do
+  if [ -f "$SEARCH_PATH/ocml.amdgcn.bc" ]; then
+    ROCM_LIB=$SEARCH_PATH
+    break
+  fi
+done
+if [ ! -f "$ROCM_LIB/ocml.amdgcn.bc" ]; then
+  echo "ROCm Device Libs is missing"
+  exit 1
+fi
 
 ################
 # AMDGPU target
