Link multiple targets in parallel processes
Added new function for processing each AMDGPU-TARGET. Use bash to launch multiple processes for each target so that multiple target can run llvm-lto's ThinLTO in parallel. Also fixed a few compiler bugs such as missing __oclc_ISA_version function.

diff --git a/lib/clamp-link.in b/lib/clamp-link.in
--- a/lib/clamp-link.in
+++ b/lib/clamp-link.in
@@ -128,6 +128,89 @@ fi
 #very verbose
 #VERBOSE=2
 
+_thinlto_target_helper() {
+
+  local AMDGPU_TARGET=$1
+
+  HCC_BC_LIBS="$ROCM_LIB/hc.amdgcn.bc $ROCM_LIB/opencl.amdgcn.bc $ROCM_LIB/ocml.amdgcn.bc $ROCM_LIB/ockl.amdgcn.bc $ROCM_LIB/irif.amdgcn.bc $ROCM_LIB/oclc_finite_only_off.amdgcn.bc $ROCM_LIB/oclc_daz_opt_off.amdgcn.bc $ROCM_LIB/oclc_correctly_rounded_sqrt_on.amdgcn.bc $ROCM_LIB/oclc_unsafe_math_off.amdgcn.bc"
+  HCC_EXTRA_ARCH_FILE=""
+  # select appropriate ROCm-Device-Libs per AMDGPU_TARGET
+  if [ $AMDGPU_TARGET == "gfx700" ]; then
+    OCLC_ISA_VERSION_LIB="$ROCM_LIB/oclc_isa_version_700.amdgcn.bc"
+    HCC_EXTRA_ARCH_FILE=$HCC_EXTRA_LIBRARIES_GFX700
+  elif [ $AMDGPU_TARGET == "gfx701" ]; then
+    OCLC_ISA_VERSION_LIB="$ROCM_LIB/oclc_isa_version_701.amdgcn.bc"
+    HCC_EXTRA_ARCH_FILE=$HCC_EXTRA_LIBRARIES_GFX701
+  elif [ $AMDGPU_TARGET == "gfx801" ]; then
+    OCLC_ISA_VERSION_LIB="$ROCM_LIB/oclc_isa_version_801.amdgcn.bc"
+    HCC_EXTRA_ARCH_FILE=$HCC_EXTRA_LIBRARIES_GFX801
+  elif [ $AMDGPU_TARGET == "gfx802" ]; then
+    OCLC_ISA_VERSION_LIB="$ROCM_LIB/oclc_isa_version_802.amdgcn.bc"
+    HCC_EXTRA_ARCH_FILE=$HCC_EXTRA_LIBRARIES_GFX802
+  elif [ $AMDGPU_TARGET == "gfx803" ]; then
+    OCLC_ISA_VERSION_LIB="$ROCM_LIB/oclc_isa_version_803.amdgcn.bc"
+    HCC_EXTRA_ARCH_FILE=$HCC_EXTRA_LIBRARIES_GFX803
+  elif [ $AMDGPU_TARGET == "gfx900" ]; then
+    OCLC_ISA_VERSION_LIB="$ROCM_LIB/oclc_isa_version_900.amdgcn.bc"
+    HCC_EXTRA_ARCH_FILE=$HCC_EXTRA_LIBRARIES_GFX900
+  elif [ $AMDGPU_TARGET == "gfx901" ]; then
+    OCLC_ISA_VERSION_LIB="$ROCM_LIB/oclc_isa_version_901.amdgcn.bc"
+    HCC_EXTRA_ARCH_FILE=$HCC_EXTRA_LIBRARIES_GFX901
+  fi
+  HCC_BC_LIBS="$HCC_BC_LIBS $OCLC_ISA_VERSION_LIB $HCC_EXTRA_LIBRARIES $HCC_EXTRA_ARCH_FILE"
+
+  # prepare all kernels for opt and llc passes by linking with rocdl lib
+  declare -a LINK_IMPORTED_KERNEL_ARGS
+  for KERNEL in ${LinkKernelArgs[@]}
+  do
+    LINK_IMPORTED_KERNEL_ARGS+=( $KERNEL-$AMDGPU_TARGET.imported.bc )
+    $LINK -suppress-warnings -o $KERNEL-$AMDGPU_TARGET.imported.bc $KERNEL.thinlto.imported.bc $HCC_BC_LIBS
+  done
+
+  if [ $VERBOSE != 0 ]; then
+    echo "Imported Kernels: ${LINK_IMPORTED_KERNEL_ARGS[@]}"
+    echo ""
+  fi
+
+  # perform parallel opt and llc in-program
+  $LTO -thinlto -thinlto-action=optllc "${LINK_IMPORTED_KERNEL_ARGS[@]}" -select-accelerator-code -dce -globaldce -always-inline -mtriple amdgcn--amdhsa-amdgiz -mcpu=$AMDGPU_TARGET -infer-address-spaces -amdgpu-internalize-symbols -lto-freestanding -enable-si-insert-waitcnts=0 $KMOPTOPT -codegen-opt-level=$KMOPTLLC -thinlto-save-temps="$TEMP_DIR/"
+
+  if [ $KMDUMPISA == "1" ]; then
+    $LTO -thinlto -thinlto-action=optllc "${LINK_IMPORTED_KERNEL_ARGS[@]}" -select-accelerator-code -dce -globaldce -always-inline -mtriple amdgcn--amdhsa-amdgiz -mcpu=$AMDGPU_TARGET -infer-address-spaces -amdgpu-internalize-symbols -lto-freestanding -dump-isa -enable-si-insert-waitcnts=0 $KMOPTOPT -codegen-opt-level=$KMOPTLLC
+    for f in $TEMP_DIR/*.thinlto.isa; do bn="${f##*/}"; cp "$f" "${KMDUMPDIR}/dump-${bn%%.*}.isa"; done
+  fi
+
+  declare -a ISABIN_FILES
+  # collect the ISABIN files for lld linking
+  for KERNEL in ${LINK_IMPORTED_KERNEL_ARGS[@]}
+  do
+    ISABIN_FILES+=( $KERNEL.thinlto.isabin )
+  done
+
+  if [ $VERBOSE != 0 ]; then
+    echo "ISABIN Kernels: ${ISABIN_FILES[@]}"
+    echo ""
+  fi
+
+  # combine all ISABIN files into HSACO format
+  $LLD -shared ${ISABIN_FILES[@]} -o $2
+  ret=$?
+  if [ $ret != 0 ]; then
+    echo "Generating AMD GCN kernel failed in ld.lld for target: $AMDGPU_TARGET"
+    exit $ret
+  fi
+  if [ $KMDUMPISA == "1" ]; then
+    cp $2 ${KMDUMPDIR}/dump-$AMDGPU_TARGET.hsaco
+  fi
+
+  if [ $VERBOSE != 0 ]; then
+    echo "Generated: $2"
+    echo ""
+  fi
+  unset ISABIN_FILES
+  unset LINK_IMPORTED_KERNEL_ARGS
+}
+
 # Using ThinLTO for link-time independent kernels calling in-parallel clamp-device opt and llc
 _thinlto_path() {
   declare -n LinkKernelArgs=$1
@@ -165,91 +248,28 @@ _thinlto_path() {
   $LTO -thinlto -thinlto-action=thinlink "${LinkKernelArgs[@]}" -o $TEMP_DIR/kernel.thinlto.index
   $LTO -thinlto -thinlto-action=import "${LinkKernelArgs[@]}" -thinlto-index=$TEMP_DIR/kernel.thinlto.index -import-instr-limit=1048576 -force-import-weak
 
-  declare -a ISABIN_FILES
+  declare -a pids
   # for each GPU target, lower LLVM IR kernels into GCN ISA
   for AMDGPU_TARGET in ${AMDGPUTargetArray[@]}
   do
-    HCC_BC_LIBS="$ROCM_LIB/hc.amdgcn.bc $ROCM_LIB/opencl.amdgcn.bc $ROCM_LIB/ocml.amdgcn.bc $ROCM_LIB/ockl.amdgcn.bc $ROCM_LIB/irif.amdgcn.bc $OCLC_ISA_VERSION_LIB $ROCM_LIB/oclc_finite_only_off.amdgcn.bc $ROCM_LIB/oclc_daz_opt_off.amdgcn.bc $ROCM_LIB/oclc_correctly_rounded_sqrt_on.amdgcn.bc $ROCM_LIB/oclc_unsafe_math_off.amdgcn.bc"
-    HCC_EXTRA_ARCH_FILE=""
-    # select appropriate ROCm-Device-Libs per AMDGPU_TARGET
-    if [ $AMDGPU_TARGET == "gfx700" ]; then
-      OCLC_ISA_VERSION_LIB="$ROCM_LIB/oclc_isa_version_700.amdgcn.bc"
-      HCC_EXTRA_ARCH_FILE=$HCC_EXTRA_LIBRARIES_GFX700
-    elif [ $AMDGPU_TARGET == "gfx701" ]; then
-      OCLC_ISA_VERSION_LIB="$ROCM_LIB/oclc_isa_version_701.amdgcn.bc"
-      HCC_EXTRA_ARCH_FILE=$HCC_EXTRA_LIBRARIES_GFX701
-    elif [ $AMDGPU_TARGET == "gfx801" ]; then
-      OCLC_ISA_VERSION_LIB="$ROCM_LIB/oclc_isa_version_801.amdgcn.bc"
-      HCC_EXTRA_ARCH_FILE=$HCC_EXTRA_LIBRARIES_GFX801
-    elif [ $AMDGPU_TARGET == "gfx802" ]; then
-      OCLC_ISA_VERSION_LIB="$ROCM_LIB/oclc_isa_version_802.amdgcn.bc"
-      HCC_EXTRA_ARCH_FILE=$HCC_EXTRA_LIBRARIES_GFX802
-    elif [ $AMDGPU_TARGET == "gfx803" ]; then
-      OCLC_ISA_VERSION_LIB="$ROCM_LIB/oclc_isa_version_803.amdgcn.bc"
-      HCC_EXTRA_ARCH_FILE=$HCC_EXTRA_LIBRARIES_GFX803
-    elif [ $AMDGPU_TARGET == "gfx900" ]; then
-      OCLC_ISA_VERSION_LIB="$ROCM_LIB/oclc_isa_version_900.amdgcn.bc"
-      HCC_EXTRA_ARCH_FILE=$HCC_EXTRA_LIBRARIES_GFX900
-    elif [ $AMDGPU_TARGET == "gfx901" ]; then
-      OCLC_ISA_VERSION_LIB="$ROCM_LIB/oclc_isa_version_901.amdgcn.bc"
-      HCC_EXTRA_ARCH_FILE=$HCC_EXTRA_LIBRARIES_GFX901
-    fi
-    HCC_BC_LIBS="$HCC_BC_LIBS $HCC_EXTRA_LIBRARIES $HCC_EXTRA_ARCH_FILE"
+    { _thinlto_target_helper $AMDGPU_TARGET $TEMP_DIR/kernel-$AMDGPU_TARGET.hsaco; } &
 
-    # prepare all kernels for opt and llc passes by linking with rocdl lib
-    declare -a LINK_IMPORTED_KERNEL_ARGS
-    for KERNEL in ${LinkKernelArgs[@]}
-    do
-      LINK_IMPORTED_KERNEL_ARGS+=( $KERNEL-$AMDGPU_TARGET.imported.bc )
-      $LINK -suppress-warnings -o $KERNEL-$AMDGPU_TARGET.imported.bc $KERNEL.thinlto.imported.bc $HCC_BC_LIBS
-    done
-
-    if [ $VERBOSE != 0 ]; then
-      echo "Imported Kernels: ${LINK_IMPORTED_KERNEL_ARGS[@]}"
-      echo ""
-    fi
-
-    # perform parallel opt and llc in-program
-    $LTO -thinlto -thinlto-action=optllc "${LINK_IMPORTED_KERNEL_ARGS[@]}" -select-accelerator-code -dce -globaldce -always-inline -mtriple amdgcn--amdhsa-amdgiz -mcpu=$AMDGPU_TARGET -infer-address-spaces -amdgpu-internalize-symbols -lto-freestanding -enable-si-insert-waitcnts=0 $KMOPTOPT -codegen-opt-level=$KMOPTLLC -thinlto-save-temps="$TEMP_DIR/"
-
-    if [ $KMDUMPISA == "1" ]; then
-      $LTO -thinlto -thinlto-action=optllc "${LINK_IMPORTED_KERNEL_ARGS[@]}" -select-accelerator-code -dce -globaldce -always-inline -mtriple amdgcn--amdhsa-amdgiz -mcpu=$AMDGPU_TARGET -infer-address-spaces -amdgpu-internalize-symbols -lto-freestanding -dump-isa -enable-si-insert-waitcnts=0 $KMOPTOPT -codegen-opt-level=$KMOPTLLC
-      for f in $TEMP_DIR/*.thinlto.isa; do bn="${f##*/}"; cp "$f" "${KMDUMPDIR}/dump-${bn%%.*}.isa"; done
-    fi
-
-    # collect the ISABIN files for lld linking
-    for KERNEL in ${LINK_IMPORTED_KERNEL_ARGS[@]}
-    do
-      ISABIN_FILES+=( $KERNEL.thinlto.isabin )
-    done
-
-    if [ $VERBOSE != 0 ]; then
-      echo "ISABIN Kernels: ${ISABIN_FILES[@]}"
-      echo ""
-    fi
-
-    # combine all ISABIN files into HSACO format
-    $LLD -shared ${ISABIN_FILES[@]} -o $TEMP_DIR/kernel-$AMDGPU_TARGET.hsaco
-    ret=$?
-    if [ $ret != 0 ]; then
-      echo "Generating AMD GCN kernel failed in ld.lld for target: $AMDGPU_TARGET"
-      exit $ret
-    fi
-    if [ $KMDUMPISA == "1" ]; then
-      cp $TEMP_DIR/kernel-$AMDGPU_TARGET.hsaco ${KMDUMPDIR}/dump-$AMDGPU_TARGET.hsaco
-    fi
-
-    if [ $VERBOSE != 0 ]; then
-      echo "Generated: $TEMP_DIR/kernel-$AMDGPU_TARGET.hsaco"
-      echo ""
-    fi
+    # error handling
+    pids+=("${pids[@]}" "$!")
 
     # augment arguments to clang-offload-bundler
     CLANG_OFFLOAD_BUNDLER_INPUTS_ARGS+=",$TEMP_DIR/kernel-$AMDGPU_TARGET.hsaco"
     CLANG_OFFLOAD_BUNDLER_TARGETS_ARGS+=",hcc-amdgcn--amdhsa-$AMDGPU_TARGET"
-    unset ISABIN_FILES
-    unset LINK_IMPORTED_KERNEL_ARGS
   done
+
+  # collect all the error codes from forked processes
+  # error handling
+  for pid in ${pids[*]}; do
+    wait $pid || ret=$((ret+$?))
+  done
+  if [ $ret != 0 ]; then
+    exit $ret
+  fi
 }
 
 # Using default path for link-time opt and llc in clamp-device
