[hof] move hof invocation from clamp-hsatools to clamp-link

diff --git a/lib/clamp-link.in b/lib/clamp-link.in
--- a/lib/clamp-link.in
+++ b/lib/clamp-link.in
@@ -30,6 +30,7 @@ VERBOSE=0
 
 LOWER_OPENCL=@HAS_OPENCL@
 LOWER_HSA=@HAS_HSA@
+LOWER_HOF=@HAS_HSA_HOF@
 
 ################
 # Sanity check for HSAIL backend
@@ -51,7 +52,23 @@ if [ $LOWER_HSA == 1 ]; then
   fi
 fi
 
+################
+# Sanity check for HSA offline finalization
+################
 
+if [ $LOWER_HSA == 1 ] && [ $LOWER_HOF == 1 ]; then
+  # Path to HOF
+  HOF_BIN=@HOF_BIN@
+
+  if [ -d $HOF_BIN ] && [ -e $HOF_BIN/hof ]; then
+    # all HOF tools are available
+    LOWER_HOF=1
+  else
+    # disable HOF in case any of the required tools is missing
+    echo "WARNING: Missing HOF tools.  Disable HSA offline finalization."
+    LOWER_HOF=0
+  fi
+fi
 
 ################
 # link
@@ -178,6 +195,27 @@ if [ -n "$LINK_KERNEL_ARGS" ]; then
       popd > /dev/null
     fi
   fi
+
+  # HSA offline finalization
+  if [ $LOWER_HSA == 1 ] && [ $LOWER_HOF == 1 ]; then
+    # conduct HSA offline finalization
+    $HOF_BIN/hof -output=$TEMP_DIR/kernel.isa -brig $TEMP_DIR/kernel.brig
+    ret=$?
+    if [ $ret == 0 ]; then
+      # build a new kernel object
+      pushd . > /dev/null
+      cd $TEMP_DIR
+      $CLAMP_EMBED kernel.isa kernel_hof.o
+      popd > /dev/null
+
+      # debug purpose
+      # dump the brig
+      KMDUMPBRIG="${KMDUMPBRIG:=0}"
+      if [ $KMDUMPBRIG == "1" ]; then
+        cp $TEMP_DIR/kernel.isa ./dump.isa
+      fi
+    fi
+  fi
   
   if [ $ret == 0 ]; then
     # link everything together
@@ -207,6 +245,10 @@ if [ -e $TEMP_DIR/kernel_spir.o ]; then
   rm $TEMP_DIR/kernel_spir.o
 fi
 
+if [ -e $TEMP_DIR/kernel_hof.o ]; then
+  rm $TEMP_DIR/kernel_hof.o
+fi
+
 if [ -e $TEMP_DIR/kernel_hsa.o ]; then
   rm $TEMP_DIR/kernel_hsa.o
 fi
@@ -221,6 +263,10 @@ fi
 
 if [ -e $TEMP_DIR/kernel.spir ]; then
   rm $TEMP_DIR/kernel.spir
+fi
+
+if [ -e $TEMP_DIR/kernel.isa ]; then
+  rm $TEMP_DIR/kernel.isa
 fi
 
 if [ -e $TEMP_DIR/kernel.brig ]; then
