[Config][CMake][Driver] remove HSAIL as a possible backend target
HCC would use AMDGPU as the only backend target from now on.

diff --git a/lib/clamp-device.in b/lib/clamp-device.in
--- a/lib/clamp-device.in
+++ b/lib/clamp-device.in
@@ -38,7 +38,6 @@ AS=$BINDIR/llvm-as
 OPT=$BINDIR/opt
 LLC=$BINDIR/llc
 LINK=$BINDIR/llvm-link
-MATHLIB=$BINDIR/../../lib
 LIB=$BINDIR/../lib
 HSATOOLS=$BINDIR/clamp-hsatools
 
@@ -49,7 +48,7 @@ HSATOOLS=$BINDIR/clamp-hsatools
 VERBOSE=0
 
 ################
-# AMDGPU target 
+# AMDGPU target
 ################
 
 AMDGPU_TARGET=@AMDGPU_TARGET@
@@ -76,13 +75,7 @@ do
   esac
 done
 
-HSA_USE_AMDGPU_BACKEND=@HSA_USE_AMDGPU_BACKEND@
-
-if [ $HSA_USE_AMDGPU_BACKEND == "ON" ]; then
-  KM_USE_AMDGPU="${KM_USE_AMDGPU:=1}"
-fi
-
-# emit HSAIL/BRIG kernel
+# emit GCN ISA kernel
 if [ "$3" == "--hsa" ]; then
     if [ $KMDUMPLLVM == "1" ]; then
       cp $1 ./dump.input.bc
@@ -101,24 +94,18 @@ if [ "$3" == "--hsa" ]; then
     fi
 
     if [ $? == 1 ]; then
-      echo "Generating HSAIL BRIG kernel failed"
+      echo "Generating AMD GCN kernel failed"
       exit 1
     fi
 
     # remove special section information for AMDGPU backend
-    if [ $KM_USE_AMDGPU ] ; then
-      $OPT -load $LIB/LLVMRemoveSpecialSection@CMAKE_SHARED_LIBRARY_SUFFIX@ \
-           -remove-special-section -S < $2.promote.ll.orig -o $2.promote.ll.orig.new
-      if [ $? == 0 ]; then
-        mv -f $2.promote.ll.orig.new $2.promote.ll.orig
-      fi
+    $OPT -load $LIB/LLVMRemoveSpecialSection@CMAKE_SHARED_LIBRARY_SUFFIX@ \
+         -remove-special-section -S < $2.promote.ll.orig -o $2.promote.ll.orig.new
+    if [ $? == 0 ]; then
+      mv -f $2.promote.ll.orig.new $2.promote.ll.orig
     fi
 
-    if [ $KM_USE_AMDGPU ] ; then
-      sed "s/addrspacecast /bitcast /g" < $2.promote.ll.orig > $2.promote.ll
-    else
-      sed "s/call /call spir_func /g" < $2.promote.ll.orig | sed "s/addrspacecast /bitcast /g" > $2.promote.ll
-    fi
+    sed "s/addrspacecast /bitcast /g" < $2.promote.ll.orig > $2.promote.ll
 
     if [ $KMDUMPLLVM == "1" ]; then
       cp $2.promote.ll ./dump.promote.ll
@@ -127,13 +114,9 @@ if [ "$3" == "--hsa" ]; then
     $AS -o $2.promote.bc $2.promote.ll
 
     if [ $VERBOSE == 1 ]; then
-      echo "Generating HSA Brig kernel"
+      echo "Generating AMD GCN kernel"
     fi
-    if [ $KM_USE_AMDGPU ] ; then
-      $LINK $2.promote.bc -o $2 2>/dev/null
-    else
-      $LINK $2.promote.bc $MATHLIB/hsa_math.bc -o $2 2>/dev/null
-    fi
+    $LINK $2.promote.bc -o $2 2>/dev/null
 
     if [ $KMDUMPLLVM == "1" ]; then
       cp $2 ./dump.hsa_math_linked.bc
