Use functions to separate ThinLTO and default path
The code is more readable when we separate the logic between ThinLTO and default paths. We want to run default path when KMTHINLTO is unset or null. Also, added comments to describe differences of ThinLTO path.

diff --git a/lib/clamp-link.in b/lib/clamp-link.in
--- a/lib/clamp-link.in
+++ b/lib/clamp-link.in
@@ -109,7 +109,125 @@ fi
 #very verbose
 #VERBOSE=2
 
+# Using ThinLTO for link-time independent kernels calling in-parallel clamp-device opt and llc
+_thinlto_path() {
+  declare -n LinkKernelArgs=$1
+  declare -n AMDGPUTargetArray=$2
 
+  if [ $VERBOSE != 0 ]; then
+    echo "Generating AMD GCN Kernels: ${LinkKernelArgs[@]}"
+  fi
+
+  # create module summaries for each kernel and perform cross-module importing
+  for KERNEL in ${LinkKernelArgs[@]} ; do
+    $OPT -thinlto-bc -disable-opt -module-summary $KERNEL -o $KERNEL
+  done
+  $LTO -thinlto -thinlto-action=thinlink "${LinkKernelArgs[@]}" -o $TEMP_DIR/kernel.thinlto.index
+  $LTO -thinlto -thinlto-action=import "${LinkKernelArgs[@]}" -thinlto-index=$TEMP_DIR/kernel.thinlto.index -import-instr-limit=1048576 -force-import-weak
+
+  declare -a pids
+  declare -a ISABIN_FILES
+  MAX_LIMIT=8
+
+  # for each GPU target, lower LLVM IR kernels into GCN ISA
+  for KERNEL in ${LinkKernelArgs[@]}
+  do
+    if [ $VERBOSE != 0 ]; then
+      echo "Processing: $KERNEL"
+    fi
+    # Only allow at most $MAX_LIMIT sub-processes
+    if [ $(jobs 2>&1 | grep -c Running) -ge "$MAX_LIMIT" ] ; then
+      for pid in ${pids[*]}; do
+        wait $pid || ret=$((ret+$?))
+      done
+      pids=("")
+    fi
+
+    # Perform clamp-device's opt and llc on each kernel individually in parallel
+    i=0
+    for AMDGPU_TARGET in ${AMDGPUTargetArray[@]}
+    do
+      { $CLAMP_DEVICE $KERNEL.thinlto.imported.bc $KERNEL-$AMDGPU_TARGET.isabin --amdgpu-target=$AMDGPU_TARGET; } &
+      # error handling
+      pids=("${pids[@]}" "$!")
+
+      # Collect the ISABIN files for later lld linking
+      ISABIN_FILES[$i]="${ISABIN_FILES[$i]} $KERNEL-$AMDGPU_TARGET.isabin"
+
+      if [ $VERBOSE != 0 ]; then
+        echo "Constructing: $KERNEL-$AMDGPU_TARGET.isabin"
+      fi
+      i+=1
+    done
+  done
+
+  # collect all the error codes from forked processes
+  # error handling
+  for pid in ${pids[*]}; do
+    wait $pid || ret=$((ret+$?))
+  done
+  if [ $ret != 0 ]; then
+    exit $ret
+  fi
+
+  i=0
+  for AMDGPU_TARGET in ${AMDGPUTargetArray[@]} ; do
+    # Combine all .isabin files into HSACO format
+    $LLD -shared ${ISABIN_FILES[$i]} -o $KERNEL-$AMDGPU_TARGET.hsaco
+    ret=$?
+    if [ $ret != 0 ]; then
+      echo "Generating AMD GCN kernel failed in ld.lld for target: $AMDGPU_TARGET"
+      exit $ret
+    fi
+    if [ $KMDUMPISA == "1" ]; then
+      cp $KERNEL-$AMDGPU_TARGET.hsaco ${KMDUMPDIR}/dump-$AMDGPU_TARGET.hsaco
+    fi
+
+    if [ $VERBOSE != 0 ]; then
+      echo "Generated: $KERNEL-$AMDGPU_TARGET.hsaco"
+    fi
+
+    # augment arguments to clang-offload-bundler
+    CLANG_OFFLOAD_BUNDLER_INPUTS_ARGS+=",$KERNEL-$AMDGPU_TARGET.hsaco"
+    CLANG_OFFLOAD_BUNDLER_TARGETS_ARGS+=",hcc-amdgcn--amdhsa-$AMDGPU_TARGET"
+    i+=1
+  done
+}
+
+# Using default path for link-time opt and llc in clamp-device
+_default_path() {
+  declare -n LinkKernelArgs=$1
+  declare -n AMDGPUTargetArray=$2
+
+  # combine kernel sections together
+  $LINK "${LinkKernelArgs[@]}" | $OPT -always-inline - -o $TEMP_DIR/kernel.bc
+
+  if [ $VERBOSE == 1 ]; then
+    echo "Generating AMD GCN kernel"
+  fi
+
+  declare -a pids
+  # for each GPU target, lower to GCN ISA in HSACO format
+  for AMDGPU_TARGET in ${AMDGPUTargetArray[@]}; do
+    { $CLAMP_DEVICE $TEMP_DIR/kernel.bc $TEMP_DIR/kernel-$AMDGPU_TARGET.hsaco --amdgpu-target=$AMDGPU_TARGET; } &
+
+    # error handling
+    pids+=("${pids[@]}" "$!")
+
+    # augment arguments to clang-offload-bundler
+    CLANG_OFFLOAD_BUNDLER_INPUTS_ARGS+=",$TEMP_DIR/kernel-$AMDGPU_TARGET.hsaco"
+    CLANG_OFFLOAD_BUNDLER_TARGETS_ARGS+=",hcc-amdgcn--amdhsa-$AMDGPU_TARGET"
+  done
+
+  # collect all the error codes from forked processes
+  # error handling
+  for pid in ${pids[*]}; do
+    wait $pid || ret=$((ret+$?))
+  done
+  if [ $ret != 0 ]; then
+    exit $ret
+  fi
+}
 
 # gather a list of library search paths
 LIB_SEARCH_PATHS=()
@@ -407,122 +525,18 @@ ret=0
 # only do kernel lowering if there are objects given
 if [ ${#LINK_KERNEL_ARGS[@]} != 0 ]; then
 
-  if [ $KMTHINLTO == "1" ]; then
-    if [ $VERBOSE != 0 ]; then
-      echo "Generating AMD GCN Kernels: ${LINK_KERNEL_ARGS[@]}"
-    fi
+  # touch an empty object for host part, to accomodate rule required by
+  # clang-offload-bundler
+  touch $TEMP_DIR/__empty.o
 
-    # create module summaries for each kernel and perform cross-module importing
-    for KERNEL in ${LINK_KERNEL_ARGS[@]} ; do
-      $OPT -thinlto-bc -disable-opt -module-summary $KERNEL -o $KERNEL
-    done
-    $LTO -thinlto -thinlto-action=thinlink "${LINK_KERNEL_ARGS[@]}" -o $TEMP_DIR/kernel.thinlto.index
-    $LTO -thinlto -thinlto-action=import "${LINK_KERNEL_ARGS[@]}" -thinlto-index=$TEMP_DIR/kernel.thinlto.index -import-instr-limit=1048576 -force-import-weak
-
-    # touch an empty object for host part, to accomodate rule required by
-    # clang-offload-bundler
-    touch $TEMP_DIR/__empty.o
-
-    # invoke clang-offload-bundler to create kernel bundle
-    CLANG_OFFLOAD_BUNDLER_INPUTS_ARGS="-inputs=$TEMP_DIR/__empty.o"
-    CLANG_OFFLOAD_BUNDLER_TARGETS_ARGS="-targets=host-@CMAKE_SYSTEM_PROCESSOR@-unknown-linux"
-
-    declare -a pids
-    declare -a ISABIN_FILES
-    MAX_LIMIT=8
-
-    # for each GPU target, lower to GCN ISA in HSACO format
-    for KERNEL in ${LINK_KERNEL_ARGS[@]}
-    do
-      if [ $VERBOSE != 0 ]; then
-        echo "Processing: $KERNEL"
-      fi
-      # Only allow at most $MAX_LIMIT sub-processes
-      if [ $(jobs 2>&1 | grep -c Running) -ge "$MAX_LIMIT" ] ; then
-        for pid in ${pids[*]}; do
-          wait $pid || ret=$((ret+$?))
-        done
-        pids=("")
-      fi
-
-      i=0
-      for AMDGPU_TARGET in ${AMDGPU_TARGET_ARRAY[@]}
-      do
-        { $CLAMP_DEVICE $KERNEL.thinlto.imported.bc $KERNEL-$AMDGPU_TARGET.isabin --amdgpu-target=$AMDGPU_TARGET; } &
-        # error handling
-        pids=("${pids[@]}" "$!")
-
-        ISABIN_FILES[$i]="${ISABIN_FILES[$i]} $KERNEL-$AMDGPU_TARGET.isabin"
-
-        if [ $VERBOSE != 0 ]; then
-          echo "Constructing: $KERNEL-$AMDGPU_TARGET.isabin"
-        fi
-        i+=1
-      done
-    done
-  else # KMTHINLTO != 1
-    # combine kernel sections together
-    $LINK "${LINK_KERNEL_ARGS[@]}" | $OPT -always-inline - -o $TEMP_DIR/kernel.bc
-
-    # lower to GCN ISA
-    if [ $VERBOSE == 1 ]; then
-      echo "Generating AMD GCN kernel"
-    fi
-
-    # touch an empty object for host part, to accomodate rule required by
-    # clang-offload-bundler
-    touch $TEMP_DIR/__empty.o
-
-    # invoke clang-offload-bundler to create kernel bundle
-    CLANG_OFFLOAD_BUNDLER_INPUTS_ARGS="-inputs=$TEMP_DIR/__empty.o"
-    CLANG_OFFLOAD_BUNDLER_TARGETS_ARGS="-targets=host-@CMAKE_SYSTEM_PROCESSOR@-unknown-linux"
-
-    declare -a pids
-    # for each GPU target, lower to GCN ISA in HSACO format
-    for AMDGPU_TARGET in ${AMDGPU_TARGET_ARRAY[@]}; do
-      { $CLAMP_DEVICE $TEMP_DIR/kernel.bc $TEMP_DIR/kernel-$AMDGPU_TARGET.hsaco --amdgpu-target=$AMDGPU_TARGET; } &
-
-      # error handling
-      pids+=("${pids[@]}" "$!")
-
-      # augment arguments to clang-offload-bundler
-      CLANG_OFFLOAD_BUNDLER_INPUTS_ARGS+=",$TEMP_DIR/kernel-$AMDGPU_TARGET.hsaco"
-      CLANG_OFFLOAD_BUNDLER_TARGETS_ARGS+=",hcc-amdgcn--amdhsa-$AMDGPU_TARGET"
-    done
-  fi
-
-  # collect all the error codes from forked processes
-  # error handling
-  for pid in ${pids[*]}; do
-    wait $pid || ret=$((ret+$?))
-  done
-  if [ $ret != 0 ]; then
-    exit $ret
-  fi
+  # invoke clang-offload-bundler to create kernel bundle
+  CLANG_OFFLOAD_BUNDLER_INPUTS_ARGS="-inputs=$TEMP_DIR/__empty.o"
+  CLANG_OFFLOAD_BUNDLER_TARGETS_ARGS="-targets=host-@CMAKE_SYSTEM_PROCESSOR@-unknown-linux"
 
   if [ $KMTHINLTO == "1" ]; then
-    i=0
-    for AMDGPU_TARGET in ${AMDGPU_TARGET_ARRAY[@]} ; do
-      # Combine all .isabin files into HSACO format
-      $LLD -shared ${ISABIN_FILES[$i]} -o $KERNEL-$AMDGPU_TARGET.hsaco
-      ret=$?
-      if [ $ret != 0 ]; then
-        echo "Generating AMD GCN kernel failed in ld.lld for target: $AMDGPU_TARGET"
-        exit $ret
-      fi
-      if [ $KMDUMPISA == "1" ]; then
-        cp $KERNEL-$AMDGPU_TARGET.hsaco ${KMDUMPDIR}/dump-$AMDGPU_TARGET.hsaco
-      fi
-
-      if [ $VERBOSE != 0 ]; then
-        echo "Generated: $KERNEL-$AMDGPU_TARGET.hsaco"
-      fi
-
-      # augment arguments to clang-offload-bundler
-      CLANG_OFFLOAD_BUNDLER_INPUTS_ARGS+=",$KERNEL-$AMDGPU_TARGET.hsaco"
-      CLANG_OFFLOAD_BUNDLER_TARGETS_ARGS+=",hcc-amdgcn--amdhsa-$AMDGPU_TARGET"
-      i+=1
-    done
+    _thinlto_path LINK_KERNEL_ARGS AMDGPU_TARGET_ARRAY
+  else
+    _default_path LINK_KERNEL_ARGS AMDGPU_TARGET_ARRAY
   fi
 
   if [ $VERBOSE != 0 ]; then
