[Link] ThinLTO base implementation

diff --git a/lib/clamp-device.in b/lib/clamp-device.in
--- a/lib/clamp-device.in
+++ b/lib/clamp-device.in
@@ -213,7 +213,7 @@ if [ $KMDUMPLLVM == "1" ]; then
   cp $2.opt.bc ${KMDUMPDIR}/dump-$AMDGPU_TARGET.opt.bc
 fi
 
-$LLC $KMOPTLLC -mtriple amdgcn--amdhsa-amdgiz -mcpu=$AMDGPU_TARGET -filetype=obj -enable-si-insert-waitcnts=0 -o $2.isabin $2.opt.bc
+$LLC $KMOPTLLC -mtriple amdgcn--amdhsa-amdgiz -mcpu=$AMDGPU_TARGET -filetype=obj -enable-si-insert-waitcnts=0 -o $2 $2.opt.bc
 
 # error handling for llc
 RETVAL=$?
@@ -223,23 +223,23 @@ if [ $RETVAL != 0 ]; then
 fi
 
 if [ $KMDUMPISA == "1" ]; then
-  cp $2.isabin ./dump-$AMDGPU_TARGET.isabin
+  cp $2 ./dump-$AMDGPU_TARGET.isabin
   $LLC $KMOPTLLC -mtriple amdgcn--amdhsa-amdgiz -mcpu=$AMDGPU_TARGET -filetype=asm -enable-si-insert-waitcnts=0 -o $2.isa $2.opt.bc
   mv $2.isa ${KMDUMPDIR}/dump-$AMDGPU_TARGET.isa
 fi
 
-$LLD -shared $2.isabin -o $2
+#$LLD -shared $2.isabin -o $2
 
 # error handling for ld.lld
-RETVAL=$?
-if [ $RETVAL != 0 ]; then
-  echo "Generating AMD GCN kernel failed in ld.lld for target: $AMDGPU_TARGET"
-  exit $RETVAL
-fi
+#RETVAL=$?
+#if [ $RETVAL != 0 ]; then
+#  echo "Generating AMD GCN kernel failed in ld.lld for target: $AMDGPU_TARGET"
+#  exit $RETVAL
+#fi
 
-if [ $KMDUMPISA == "1" ]; then
-  cp $2 ${KMDUMPDIR}/dump-$AMDGPU_TARGET.hsaco
-fi
+#if [ $KMDUMPISA == "1" ]; then
+#  cp $2 ${KMDUMPDIR}/dump-$AMDGPU_TARGET.hsaco
+#fi
 
 # remove temp file
-rm -f $2.promote.bc $2.linked.bc $2.opt.bc $2.isabin $2.isa
+rm -f $2.promote.bc $2.linked.bc $2.opt.bc $2.isa
diff --git a/lib/clamp-link.in b/lib/clamp-link.in
--- a/lib/clamp-link.in
+++ b/lib/clamp-link.in
@@ -7,6 +7,9 @@ then
   set -x
 fi
 
+# dump the isa
+KMDUMPISA="${KMDUMPISA:=0}"
+
 # check number of arguments
 if [ "$#" -eq 0 ]; then
   echo "$0 is NOT recommended to be directly used" >&2
@@ -18,8 +21,10 @@ KMDUMPBUNDLE="${KMDUMPBUNDLE:=0}"
 
 BINDIR=$(dirname $0)
 LINK=$BINDIR/llvm-link
+LTO=$BINDIR/llvm-lto
 OPT=$BINDIR/opt
 CLAMP_DEVICE=$BINDIR/clamp-device
+LLD=$BINDIR/ld.lld
 CLAMP_EMBED=$BINDIR/clamp-embed
 CLANG_OFFLOAD_BUNDLER=$BINDIR/clang-offload-bundler
 
@@ -148,6 +153,7 @@ do
     ################################################
     -dump-isa)
     export KMDUMPISA=1
+    KMDUMPISA=1
     continue
     ;;
     -dump-llvm)
@@ -389,7 +395,13 @@ ret=0
 if [ ${#LINK_KERNEL_ARGS[@]} != 0 ]; then
 
   # combine kernel sections together
-  $LINK "${LINK_KERNEL_ARGS[@]}" | $OPT -always-inline - -o $TEMP_DIR/kernel.bc
+  #$LINK "${LINK_KERNEL_ARGS[@]}" | $OPT -always-inline - -o $TEMP_DIR/kernel.bc
+  echo "Kernels: ${LINK_KERNEL_ARGS[@]}"
+  for KERNEL in ${LINK_KERNEL_ARGS[@]} ; do
+    $OPT -thinlto-bc -disable-opt $KERNEL -o $KERNEL
+  done
+  $LTO -thinlto-action=thinlink "${LINK_KERNEL_ARGS[@]}" -o $TEMP_DIR/kernel.thinlto.index
+  $LTO -thinlto-action=import "${LINK_KERNEL_ARGS[@]}" -thinlto-index=$TEMP_DIR/kernel.thinlto.index
 
   # lower to GCN ISA
   if [ $VERBOSE == 1 ]; then
@@ -403,29 +415,61 @@ if [ ${#LINK_KERNEL_ARGS[@]} != 0 ]; then
   # invoke clang-offload-bundler to create kernel bundle
   CLANG_OFFLOAD_BUNDLER_INPUTS_ARGS="-inputs=$TEMP_DIR/__empty.o"
   CLANG_OFFLOAD_BUNDLER_TARGETS_ARGS="-targets=host-x86_64-unknown-linux"
-
+  echo "Clamp-device inputs and outputs:"
   declare -a pids
+  declare -a ISABIN_FILES
+  MAX_LIMIT=8
   # for each GPU target, lower to GCN ISA in HSACO format
-  for AMDGPU_TARGET in ${AMDGPU_TARGET_ARRAY[@]}; do
-    { $CLAMP_DEVICE $TEMP_DIR/kernel.bc $TEMP_DIR/kernel-$AMDGPU_TARGET.hsaco --amdgpu-target=$AMDGPU_TARGET; } &
+  for AMDGPU_TARGET in ${AMDGPU_TARGET_ARRAY[@]}
+  do
+    for KERNEL in ${LINK_KERNEL_ARGS[@]}
+    do
+      #{ $CLAMP_DEVICE $TEMP_DIR/kernel.bc $TEMP_DIR/kernel-$AMDGPU_TARGET.hsaco --amdgpu-target=$AMDGPU_TARGET; } &
+      echo "$KERNEL"
+      # Only allow at most $MAX_LIMIT sub-processes
+      if [ $(jobs 2>&1 | grep -c Running) -ge "$MAX_LIMIT" ] ; then
+        for pid in ${pids[*]}; do
+          wait $pid || ret=$((ret+$?))
+        done
+        pids=("")
+      fi
+      { $CLAMP_DEVICE $KERNEL.thinlto.imported.bc $KERNEL-$AMDGPU_TARGET.isabin --amdgpu-target=$AMDGPU_TARGET; } &
+      # error handling
+      pids=("${pids[@]}" "$!")
+      ISABIN_FILES=("${ISABIN_FILES[@]}" "$KERNEL-$AMDGPU_TARGET.isabin")
+      echo "$KERNEL-$AMDGPU_TARGET.isabin"
+    done
 
+    # collect all the error codes from forked processes
     # error handling
-    pids+=("${pids[@]}" "$!")
+    for pid in ${pids[*]}; do
+      wait $pid || ret=$((ret+$?))
+    done
+    pids=("")
+    if [ $ret != 0 ]; then
+      exit $ret
+    fi
+
+    # Combine all .isabin files into HSACO format
+    $LLD -shared "${ISABIN_FILES[@]}" -o $KERNEL-$AMDGPU_TARGET.hsaco
+    ret=$?
+    if [ $ret != 0 ]; then
+      echo "Generating AMD GCN kernel failed in ld.lld for target: $AMDGPU_TARGET"
+      exit $ret
+    fi
+    if [ $KMDUMPISA == "1" ]; then
+      cp $KERNEL-$AMDGPU_TARGET.hsaco ${KMDUMPDIR}/dump-$AMDGPU_TARGET.hsaco
+    fi
+
+    ISABIN_FILES=("")
+    echo "$KERNEL-$AMDGPU_TARGET.hsaco"
 
     # augment arguments to clang-offload-bundler
-    CLANG_OFFLOAD_BUNDLER_INPUTS_ARGS+=",$TEMP_DIR/kernel-$AMDGPU_TARGET.hsaco"
+    CLANG_OFFLOAD_BUNDLER_INPUTS_ARGS+=",$KERNEL-$AMDGPU_TARGET.hsaco"
     CLANG_OFFLOAD_BUNDLER_TARGETS_ARGS+=",hcc-amdgcn--amdhsa-$AMDGPU_TARGET"
   done
 
-  # collect all the error codes from forked processes
-  # error handling
-  for pid in ${pids[*]}; do
-    wait $pid || ret=$((ret+$?))
-  done
-  if [ $ret != 0 ]; then
-    exit $ret
-  fi
-
+  echo "Finished clamp-device"
 
   # invoke clang-offload-bundler
   $CLANG_OFFLOAD_BUNDLER -type=o $CLANG_OFFLOAD_BUNDLER_INPUTS_ARGS $CLANG_OFFLOAD_BUNDLER_TARGETS_ARGS -outputs=$TEMP_DIR/kernel.bundle
