Implementing ThinLTO Link Time Phase 2 (#578)
* Use llvm-lto for optllc instead of clamp-device

* Enable select-accelerator-code for thinlto

* Perform rocdl linking after imported kernels

* Implement KMDUMPISA to perform ISA dump with ThinLTO

* Fix loading empty string on multiple targets

* Link multiple targets in parallel processes

Added new function for processing each AMDGPU-TARGET. Use bash to launch multiple processes for each target so that multiple target can run llvm-lto's ThinLTO in parallel. Also fixed a few compiler bugs such as missing __oclc_ISA_version function.

* Merge clang_tot_upgrade and submodule into thinlto4

* Added kernel splitting before ThinLTO

* Fix bugs in splitting HCC kernels

* Kernel Split: add options to control splitting threshold condition and number of splitted files

* Add KMTHINLTO to unit test Env Var, change kernel splitting configuration and fix small bugs

* Fix HCC Unit Test failures and add LLVM dump

* Fix unit tests in default path

* Revert to using loadable passes

* Add comments and verbose guards in clamp-link.in

* Fine Tune Kernel Splitting Number of Files

diff --git a/lib/clamp-link.in b/lib/clamp-link.in
--- a/lib/clamp-link.in
+++ b/lib/clamp-link.in
@@ -7,8 +7,27 @@ then
   set -x
 fi
 
+# directory where files are dumped
+KMDUMPDIR="${KMDUMPDIR:=.}"
+
+# dump the LLVM bitcode
+KMDUMPLLVM="${KMDUMPLLVM:=0}"
+
 # dump the isa
 KMDUMPISA="${KMDUMPISA:=0}"
+
+# pass extra options to OPT
+# KMOPTOPT can be used to pass last-minute options to opt in the backend
+# if not set, then "-O3" would be passed to opt
+KMOPTOPT="${KMOPTOPT:="-O3"}"
+
+# pass extra options to LLC
+# KMOPTLLC can be used to pass last-minute options to llc in the backend
+# if not set, then 2 will be passed to llc
+KMOPTLLC="${KMOPTLLC:=2}"
+
+# enable LLVM hijacking
+KMHACKLLVM="${KMHACKLLVM:=0}"
 
 # determine if we want to use ThinLTO
 KMTHINLTO="${KMTHINLTO:=0}"
@@ -25,7 +44,9 @@ KMDUMPBUNDLE="${KMDUMPBUNDLE:=0}"
 BINDIR=$(dirname $0)
 LINK=$BINDIR/llvm-link
 LTO=$BINDIR/llvm-lto
+SPLIT=$BINDIR/llvm-split
 OPT=$BINDIR/opt
+LOAD_PASS_LIB=$BINDIR/../lib
 CLAMP_DEVICE=$BINDIR/clamp-device
 LLD=$BINDIR/ld.lld
 CLAMP_EMBED=$BINDIR/clamp-embed
@@ -111,54 +132,179 @@ fi
 #very verbose
 #VERBOSE=2
 
-# Using ThinLTO for link-time independent kernels calling in-parallel clamp-device opt and llc
+# This ThinLTO helper function performs the ThinLTO Link Time for the specified AMDGPU target.
+# Using a helper function allows us to launch multiple helper functions in parallel for different gfx targets.
+_thinlto_target_helper() {
+
+  local AMDGPU_TARGET=$1
+
+  # prepare the rocdl libraries to be linked
+  HCC_BC_LIBS="$ROCM_LIB/hc.amdgcn.bc $ROCM_LIB/opencl.amdgcn.bc $ROCM_LIB/ocml.amdgcn.bc $ROCM_LIB/ockl.amdgcn.bc $ROCM_LIB/irif.amdgcn.bc $ROCM_LIB/oclc_finite_only_off.amdgcn.bc $ROCM_LIB/oclc_daz_opt_off.amdgcn.bc $ROCM_LIB/oclc_correctly_rounded_sqrt_on.amdgcn.bc $ROCM_LIB/oclc_unsafe_math_off.amdgcn.bc"
+  HCC_EXTRA_ARCH_FILE=""
+  # select appropriate ROCm-Device-Libs per AMDGPU_TARGET
+  if [ $AMDGPU_TARGET == "gfx700" ]; then
+    OCLC_ISA_VERSION_LIB="$ROCM_LIB/oclc_isa_version_700.amdgcn.bc"
+    HCC_EXTRA_ARCH_FILE=$HCC_EXTRA_LIBRARIES_GFX700
+  elif [ $AMDGPU_TARGET == "gfx701" ]; then
+    OCLC_ISA_VERSION_LIB="$ROCM_LIB/oclc_isa_version_701.amdgcn.bc"
+    HCC_EXTRA_ARCH_FILE=$HCC_EXTRA_LIBRARIES_GFX701
+  elif [ $AMDGPU_TARGET == "gfx801" ]; then
+    OCLC_ISA_VERSION_LIB="$ROCM_LIB/oclc_isa_version_801.amdgcn.bc"
+    HCC_EXTRA_ARCH_FILE=$HCC_EXTRA_LIBRARIES_GFX801
+  elif [ $AMDGPU_TARGET == "gfx802" ]; then
+    OCLC_ISA_VERSION_LIB="$ROCM_LIB/oclc_isa_version_802.amdgcn.bc"
+    HCC_EXTRA_ARCH_FILE=$HCC_EXTRA_LIBRARIES_GFX802
+  elif [ $AMDGPU_TARGET == "gfx803" ]; then
+    OCLC_ISA_VERSION_LIB="$ROCM_LIB/oclc_isa_version_803.amdgcn.bc"
+    HCC_EXTRA_ARCH_FILE=$HCC_EXTRA_LIBRARIES_GFX803
+  elif [ $AMDGPU_TARGET == "gfx900" ]; then
+    OCLC_ISA_VERSION_LIB="$ROCM_LIB/oclc_isa_version_900.amdgcn.bc"
+    HCC_EXTRA_ARCH_FILE=$HCC_EXTRA_LIBRARIES_GFX900
+  elif [ $AMDGPU_TARGET == "gfx901" ]; then
+    OCLC_ISA_VERSION_LIB="$ROCM_LIB/oclc_isa_version_901.amdgcn.bc"
+    HCC_EXTRA_ARCH_FILE=$HCC_EXTRA_LIBRARIES_GFX901
+  fi
+  HCC_BC_LIBS="$HCC_BC_LIBS $OCLC_ISA_VERSION_LIB $HCC_EXTRA_LIBRARIES $HCC_EXTRA_ARCH_FILE"
+
+  # prepare all kernels for opt and llc passes by linking with rocdl library
+  declare -a LINK_IMPORTED_KERNEL_ARGS
+  for KERNEL in ${LinkKernels[@]}
+  do
+    LINK_IMPORTED_KERNEL_ARGS+=( $KERNEL-$AMDGPU_TARGET.imported.bc )
+    $LINK -suppress-warnings -o $KERNEL-$AMDGPU_TARGET.imported.bc $KERNEL.thinlto.imported.bc $HCC_BC_LIBS
+  done
+
+  if [ $VERBOSE != 0 ]; then
+    echo "Imported Kernels: ${LINK_IMPORTED_KERNEL_ARGS[@]}"
+    echo ""
+  fi
+
+  # perform parallel opt and llc in-program llvm-lto and
+  # specify the opt and codegen passes to be added
+  $LTO -thinlto -thinlto-action=optllc "${LINK_IMPORTED_KERNEL_ARGS[@]}" -load $LOAD_PASS_LIB/LLVMSelectAcceleratorCode@CMAKE_SHARED_LIBRARY_SUFFIX@ -select-accelerator-code -dce -globaldce -always-inline -mtriple amdgcn--amdhsa-amdgiz -mcpu=$AMDGPU_TARGET -infer-address-spaces -amdgpu-internalize-symbols -lto-freestanding -enable-si-insert-waitcnts=0 $KMOPTOPT -codegen-opt-level=$KMOPTLLC -thinlto-save-temps="$TEMP_DIR/"
+
+  # since thinlto has multiple kernel files, we will dump all the optimized kernel files
+  if [ $KMDUMPLLVM == "1" ]; then
+    for f in $TEMP_DIR/*.1.opt.bc; do bn="${f##*/}"; cp "$f" "${KMDUMPDIR}/dump-$AMDGPU_TARGET.${bn%%.*}.opt.bc"; done
+  fi
+
+  # there are multiple kernels that underwent codegen as well, we will dump all of their isa files
+  if [ $KMDUMPISA == "1" ]; then
+    $LTO -thinlto -thinlto-action=optllc "${LINK_IMPORTED_KERNEL_ARGS[@]}" -load $LOAD_PASS_LIB/LLVMSelectAcceleratorCode@CMAKE_SHARED_LIBRARY_SUFFIX@ -select-accelerator-code -dce -globaldce -always-inline -mtriple amdgcn--amdhsa-amdgiz -mcpu=$AMDGPU_TARGET -infer-address-spaces -amdgpu-internalize-symbols -lto-freestanding -dump-isa -enable-si-insert-waitcnts=0 $KMOPTOPT -codegen-opt-level=$KMOPTLLC
+    for f in $TEMP_DIR/*.thinlto.isa; do bn="${f##*/}"; cp "$f" "${KMDUMPDIR}/dump-$AMDGPU_TARGET.${bn%%.*}.isa"; done
+  fi
+
+  declare -a ISABIN_FILES
+  # collect the ISABIN files for lld linking
+  for KERNEL in ${LINK_IMPORTED_KERNEL_ARGS[@]}
+  do
+    ISABIN_FILES+=( $KERNEL.thinlto.isabin )
+  done
+
+  if [ $VERBOSE != 0 ]; then
+    echo "ISABIN Kernels: ${ISABIN_FILES[@]}"
+    echo ""
+  fi
+
+  # combine all ISABIN files into HSACO format
+  $LLD -shared ${ISABIN_FILES[@]} -o $2
+  ret=$?
+  if [ $ret != 0 ]; then
+    echo "Generating AMD GCN kernel failed in ld.lld for target: $AMDGPU_TARGET"
+    exit $ret
+  fi
+  if [ $KMDUMPISA == "1" ]; then
+    cp $2 ${KMDUMPDIR}/dump-$AMDGPU_TARGET.hsaco
+  fi
+
+  if [ $VERBOSE != 0 ]; then
+    echo "Generated: $2"
+    echo ""
+  fi
+  unset ISABIN_FILES
+  unset LINK_IMPORTED_KERNEL_ARGS
+}
+
+# Using ThinLTO for performing opt and codegen on kernels in parallel
 _thinlto_path() {
 
   if [ $VERBOSE != 0 ]; then
     echo "Generating AMD GCN Kernels: ${LINK_KERNEL_ARGS[@]}"
+    echo ""
   fi
 
-  # create module summaries for each kernel and perform cross-module importing
-  for KERNEL in ${LINK_KERNEL_ARGS[@]} ; do
-    $OPT -thinlto-bc -disable-opt -module-summary $KERNEL -o $KERNEL
+  ################
+  # Determine the ROCm device libs path
+  ################
+
+  ROCM_DEVICE_LIBS_SEARCH_PATHS="@ROCM_DEVICE_LIB_PATHS@"
+  ROCM_LIB=""
+  for SEARCH_PATH in $(echo $ROCM_DEVICE_LIBS_SEARCH_PATHS | tr ";" "\n")
+  do
+    if [ -f "$SEARCH_PATH/ocml.amdgcn.bc" ]; then
+      ROCM_LIB=$SEARCH_PATH
+      break
+    fi
   done
-  $LTO -thinlto -thinlto-action=thinlink "${LINK_KERNEL_ARGS[@]}" -o $TEMP_DIR/kernel.thinlto.index
-  $LTO -thinlto -thinlto-action=import "${LINK_KERNEL_ARGS[@]}" -thinlto-index=$TEMP_DIR/kernel.thinlto.index -import-instr-limit=1048576 -force-import-weak
+  if [ ! -f "$ROCM_LIB/ocml.amdgcn.bc" ]; then
+    echo "ROCm Device Libs is missing"
+    exit 1
+  fi
+
+  unset LinkKernels
+  LinkKernels=()
+  NUM_SPLIT=4
+  NUM_KERNS_THRESHOLD=1000
+  # for each kernel, decide if we want to split the kernel file into multiple
+  for KERNEL in ${LINK_KERNEL_ARGS[@]} ; do
+    if [ $VERBOSE != 0 ]; then
+      echo "Splitting Kernel: ${KERNEL}"
+    fi
+
+    # Using llvm-split, perform kernel splitting and return number of kernels in the file
+    NUM_KERNELS=`$SPLIT "${KERNEL}" -o "${KERNEL}" -split-hcc-kernels -split-hcc-threshold $NUM_KERNS_THRESHOLD -j $NUM_SPLIT`
+
+    if [ $VERBOSE != 0 ]; then
+      echo "Num Kerns: $NUM_KERNELS Num Kerns Threshold: $NUM_KERNS_THRESHOLD"
+    fi
+
+    # If number of kernels in the file exceeds the threshold, we will need to add each sub file into the array for LTO later
+    # Otherwise we will generate the module summary for the original kernel file for ThinLTO indexing later
+    if [ $NUM_KERNELS -le $NUM_KERNS_THRESHOLD ]; then
+      $OPT -thinlto-bc -disable-opt -module-summary $KERNEL -o $KERNEL
+      LinkKernels+=( "$KERNEL" )
+    else
+      if [ $VERBOSE != 0 ]; then
+        echo "  Splitted Number of Files: $NUM_SPLIT"
+      fi
+      for ((SUBKERNEL=0; SUBKERNEL < NUM_SPLIT; SUBKERNEL++)) ; do
+        $OPT -thinlto-bc -disable-opt -module-summary $KERNEL$SUBKERNEL -o $KERNEL$SUBKERNEL.bc
+        LinkKernels+=( "$KERNEL$SUBKERNEL.bc" )
+      done
+    fi
+  done
+
+  if [ $VERBOSE != 0 ]; then
+    echo "Splitted Kernels: ${LinkKernels[@]}"
+    echo ""
+  fi
+
+  # perform ThinLTO indexing and cross-module importing
+  $LTO -thinlto -thinlto-action=thinlink "${LinkKernels[@]}" -o $TEMP_DIR/kernel.thinlto.index
+  $LTO -thinlto -thinlto-action=import "${LinkKernels[@]}" -thinlto-index=$TEMP_DIR/kernel.thinlto.index -import-instr-limit=1048576 -force-import-weak
 
   declare -a pids
-  declare -a ISABIN_FILES
-  MAX_LIMIT=8
-
-  # for each GPU target, lower LLVM IR kernels into GCN ISA
-  for KERNEL in ${LINK_KERNEL_ARGS[@]}
+  # for each GPU target, lower LLVM IR kernels into GCN ISA in parallel
+  for AMDGPU_TARGET in ${AMDGPU_TARGET_ARRAY[@]}
   do
-    if [ $VERBOSE != 0 ]; then
-      echo "Processing: $KERNEL"
-    fi
-    # Only allow at most $MAX_LIMIT sub-processes
-    if [ $(jobs 2>&1 | grep -c Running) -ge "$MAX_LIMIT" ] ; then
-      for pid in ${pids[*]}; do
-        wait $pid || ret=$((ret+$?))
-      done
-      pids=("")
-    fi
+    { _thinlto_target_helper $AMDGPU_TARGET $TEMP_DIR/kernel-$AMDGPU_TARGET.hsaco; } &
 
-    # Perform clamp-device's opt and llc on each kernel individually in parallel
-    i=0
-    for AMDGPU_TARGET in ${AMDGPU_TARGET_ARRAY[@]}
-    do
-      { $CLAMP_DEVICE $KERNEL.thinlto.imported.bc $KERNEL-$AMDGPU_TARGET.isabin --amdgpu-target=$AMDGPU_TARGET; } &
-      # error handling
-      pids=("${pids[@]}" "$!")
+    # error handling
+    pids=("${pids[@]}" "$!")
 
-      # Collect the ISABIN files for later lld linking
-      ISABIN_FILES[$i]="${ISABIN_FILES[$i]} $KERNEL-$AMDGPU_TARGET.isabin"
-
-      if [ $VERBOSE != 0 ]; then
-        echo "Constructing: $KERNEL-$AMDGPU_TARGET.isabin"
-      fi
-      i+=1
-    done
+    # augment arguments to clang-offload-bundler
+    CLANG_OFFLOAD_BUNDLER_INPUTS_ARGS+=",$TEMP_DIR/kernel-$AMDGPU_TARGET.hsaco"
+    CLANG_OFFLOAD_BUNDLER_TARGETS_ARGS+=",hcc-amdgcn--amdhsa-$AMDGPU_TARGET"
   done
 
   # collect all the error codes from forked processes
@@ -166,32 +312,10 @@ _thinlto_path() {
   for pid in ${pids[*]}; do
     wait $pid || ret=$((ret+$?))
   done
+  unset pids
   if [ $ret != 0 ]; then
     exit $ret
   fi
-
-  i=0
-  for AMDGPU_TARGET in ${AMDGPU_TARGET_ARRAY[@]} ; do
-    # Combine all .isabin files into HSACO format
-    $LLD -shared ${ISABIN_FILES[$i]} -o $KERNEL-$AMDGPU_TARGET.hsaco
-    ret=$?
-    if [ $ret != 0 ]; then
-      echo "Generating AMD GCN kernel failed in ld.lld for target: $AMDGPU_TARGET"
-      exit $ret
-    fi
-    if [ $KMDUMPISA == "1" ]; then
-      cp $KERNEL-$AMDGPU_TARGET.hsaco ${KMDUMPDIR}/dump-$AMDGPU_TARGET.hsaco
-    fi
-
-    if [ $VERBOSE != 0 ]; then
-      echo "Generated: $KERNEL-$AMDGPU_TARGET.hsaco"
-    fi
-
-    # augment arguments to clang-offload-bundler
-    CLANG_OFFLOAD_BUNDLER_INPUTS_ARGS+=",$KERNEL-$AMDGPU_TARGET.hsaco"
-    CLANG_OFFLOAD_BUNDLER_TARGETS_ARGS+=",hcc-amdgcn-amd-amdhsa--$AMDGPU_TARGET"
-    i+=1
-  done
 }
 
 # Using default path for link-time opt and llc in clamp-device
@@ -210,7 +334,7 @@ _default_path() {
     { $CLAMP_DEVICE $TEMP_DIR/kernel.bc $TEMP_DIR/kernel-$AMDGPU_TARGET.hsaco --amdgpu-target=$AMDGPU_TARGET; } &
 
     # error handling
-    pids+=("${pids[@]}" "$!")
+    pids=("${pids[@]}" "$!")
 
     # augment arguments to clang-offload-bundler
     CLANG_OFFLOAD_BUNDLER_INPUTS_ARGS+=",$TEMP_DIR/kernel-$AMDGPU_TARGET.hsaco"
@@ -222,6 +346,7 @@ _default_path() {
   for pid in ${pids[*]}; do
     wait $pid || ret=$((ret+$?))
   done
+  unset pids
   if [ $ret != 0 ]; then
     exit $ret
   fi
@@ -281,6 +406,10 @@ do
     # Parse dump options and export them for called
     # scripts e.g. clamp-device
     ################################################
+    --hcc-extra-libs=*)
+    HCC_EXTRA_LIBRARIES="$HCC_EXTRA_LIBRARIES ${ARG#*=}"
+    continue
+    ;;
     -dump-isa)
     export KMDUMPISA=1
     continue
